Update aks.yml

diff --git a/.github/workflows/aks.yml b/.github/workflows/aks.yml
--- a/.github/workflows/aks.yml
+++ b/.github/workflows/aks.yml
@@ -54,17 +54,23 @@ jobs:
           helm repo update
           helm install ingress-nginx ingress-nginx/ingress-nginx --create-namespace --namespace ingress-nginx
 
-      - name: Wait for ingress IP
+      - name: Wait for Ingress LB IP
         run: |
-          echo "Waiting for Ingress LB IP..."
+          echo "Waiting for Ingress LB IP to be assigned..."
           for i in {1..30}; do
             IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
             if [ -n "$IP" ]; then
+              echo "Ingress LB IP: $IP"
               echo "INGRESS_LB_IP=$IP" >> $GITHUB_ENV
               break
             fi
-            sleep 10
+            echo "Attempt $i: Waiting for IP..."
+            sleep 20
           done
+          if [ -z "$IP" ]; then
+            echo "Ingress IP not found after 30 attempts, exiting."
+            exit 1
+          fi
 
       - name: Create namespace 
         run: |
